# Generated by Django 4.2.4 on 2023-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_user_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
